name: Backup and Restore Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Action: Backup or Restore'
        required: true
        default: 'Backup'
        type: choice
        options:
          - Backup
          - Restore
      environment:
        description: 'Select Environment: dev, stage, or prod'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - prod

jobs:
  backup-restore:
    name: Execute Backup or Restore
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Azure CLI
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      # Read backend configuration from dev.json
      - name: Read Backend Configuration
        id: read-backend
        run: |
          content=$(cat backend/${{ github.event.inputs.environment }}.json)
          echo "CONFIG=${content}" >> $GITHUB_ENV

      # Run Backup or Restore based on input
      - name: Execute Backup or Restore Script
        run: |
          $env:BACKEND_CONFIG = '${{ env.CONFIG }}'
          $env:ENVIRONMENT = '${{ github.event.inputs.environment }}'

          if ('${{ github.event.inputs.action }}' -eq 'Backup') {
            Write-Host "Starting Backup Process..."
            pwsh ./script/backup.ps1 -BackendConfig $env:BACKEND_CONFIG -Environment $env:ENVIRONMENT
          } elseif ('${{ github.event.inputs.action }}' -eq 'Restore') {
            Write-Host "Starting Restore Process..."
            pwsh ./script/restore.ps1 -BackendConfig $env:BACKEND_CONFIG -Environment $env:ENVIRONMENT
          }
        shell: pwsh
